### ISSUE TITLE
Not compatible with puppet6 (actually stdlib 8.6.0)

### ISSUE THREAD

**Issue by jchonig** [deric/puppet-smartd#2]
While it's not a direct problem for puppet6, stdlib 9 and later do not support puppet6.  So I have to use 8.6.0 until I get all my machines upgraded. 

I get this error:

`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Unknown function: 'stdlib::ensure_packages'. (file: /etc/puppetlabs/code/environments/production/modules/smartd/manifests/init.pp, line: 65, column: 5) on node wraina.home.honig.net`

Removing the `stdlib::` prefix fixes the issue for me.

Thanks.

Jeff

**Comment by deric** [comment]
You should be fine using version [`v0.5.0`](https://github.com/deric/puppet-smartd/releases/tag/v0.5.0) until you're able to upgrade.

**Comment by deric** [comment]
Or you can use `v1.1.0` which should work with stdlib 8

**Comment by jchonig** [comment]
Confirmed that it works with stdlib 8.

Thanks

Jeff
